from custom_envs.envs.panda_tasks.My_panda_reach import My_PandaReachEnv
from custom_envs.envs.panda_tasks.My_panda_pick_and_place import My_PandaPickAndPlaceEnv
from custom_envs.envs.panda_tasks.My_panda_slide import My_PandaSlideEnv

from custom_envs.envs.panda_tasks.Two_panda_reach import Two_PandaReachEnv
from custom_envs.envs.panda_tasks.Three_panda_reach import Three_PandaReachEnv

from custom_envs.envs.panda_tasks.Two_panda_push import Two_PandaPushEnv
from custom_envs.envs.panda_tasks.Three_panda_push import Three_PandaPushEnv

from custom_envs.envs.panda_tasks.Two_obj_panda_push import Two_Obj_PandaPushEnv
from custom_envs.envs.panda_tasks.Three_obj_panda_push import Three_Obj_PandaPushEnv

from custom_envs.envs.panda_tasks.My_panda_reach_plate import My_PandaReachPlateEnv
from custom_envs.envs.panda_tasks.My_two_panda_reach_plate import My_TwoPandaReachPlateEnv
